Fix: fixed test errors concerning
backend.tests.test_pena_players_controller::test_get_pena_players_builds_clean_filters_and_total_pages
(failure): AttributeError: 'Query' object has no attribute 'strip'

backend.tests.test_season_competition_controller::test_helper_clean_and_page_response
(failure): TypeError: SeasonPlayerInfo.init() missing 3 required
positional arguments: 'role', 'role_color', and 'position_color'

backend.tests.test_season_competition_controller::test_register_player_in_season_success
(failure): TypeError: SeasonPlayerInfo.init() missing 3 required
positional arguments: 'role', 'role_color', and 'position_color'

backend.tests.test_season_competition_controller::test_register_players_in_season_bulk_success
(failure): TypeError: SeasonPlayerInfo.init() missing 3 required
positional arguments: 'role', 'role_color', and 'position_color'

backend.tests.test_season_competition_controller::test_update_season_player_stats_sets_partial_flags
(failure): TypeError: SeasonPlayerInfo.init() missing 3 required
positional arguments: 'role', 'role_color', and 'position_color'

backend.tests.test_season_competition_controller::test_list_season_players_success_and_filter_cleaning
(failure): TypeError: object of type 'Query' has no len()

backend.tests.test_season_competition_controller::test_list_season_players_maps_not_found
(failure): TypeError: object of type 'Query' has no len()

backend.tests.test_season_competition_controller::test_get_season_standings_success
(failure): TypeError: object of type 'Query' has no len()